/**
 * Shared banner + module-body rendering helpers for the per-tool adapters.
 *
 * The banner format is identical across Claude Code, Cursor, Windsurf, and
 * Copilot so it lives in one place to keep adapter output deterministic and
 * spec-compliant.
 *
 * See: openspec/specs/cross-platform/export-command.md (Output Structure)
 */

import type { ExportMeta, ResolvedModule } from './types';

/** Line ending for every adapter, regardless of host OS. */
export const LF = '\n';

/**
 * Render the standard banner. Five HTML comment lines per the spec, joined
 * with LF and terminated with LF. Does NOT include the MCP snippet.
 */
export function renderBanner(meta: ExportMeta): string {
  const modulesList = meta.modules.map((m) => `${m.id}@${m.version}`).join(', ');
  const lines = [
    '<!-- GENERATED BY augx export - DO NOT EDIT -->',
    `<!-- augx-version: ${meta.augxVersion} -->`,
    `<!-- generated-at: ${meta.generatedAt} -->`,
    `<!-- source-hash: ${meta.sourceHash} -->`,
    `<!-- modules: ${modulesList} -->`,
  ];
  return lines.join(LF) + LF;
}

/**
 * Render the banner followed by the optional MCP snippet body when present.
 * Returns just the header region; no trailing `---` separator or module
 * heading. The runner is responsible for emitting inter-section separators.
 */
export function renderHeaderRegion(meta: ExportMeta): string {
  const banner = renderBanner(meta);
  if (!meta.mcpSnippet) {
    return banner;
  }
  // Blank line between banner and MCP snippet body.
  return banner + LF + normalizeBody(meta.mcpSnippet);
}

/**
 * Standard footer line shared across all single-file aggregator outputs.
 */
export function renderStandardFooter(): string {
  return (
    '<!-- End of augx-generated content. Canonical modules: augment-extensions/modules/ -->' +
    LF
  );
}

/**
 * Render the concatenated body for a module's rule files.
 *
 * - Files are emitted in the order supplied (resolver guarantees alphabetical
 *   `relativePath`).
 * - Each file's content is preceded by a small HTML-comment marker recording
 *   its relative path. The marker is unobtrusive in rendered Markdown and
 *   preserves traceability without altering visible content.
 * - Files are separated by a single blank line.
 *
 * Empty modules (no rule files) produce a placeholder note so the structure
 * is still well-formed and auditable.
 */
export function renderModuleBody(module: ResolvedModule): string {
  if (module.rulesFiles.length === 0) {
    return `<!-- module ${module.id} has no rule files -->` + LF;
  }
  const blocks = module.rulesFiles.map((file) => {
    const marker = `<!-- file: ${file.relativePath} -->`;
    return marker + LF + normalizeBody(file.content);
  });
  return blocks.join(LF);
}

/**
 * Normalize a body string for inclusion in the aggregator:
 *
 * - Convert CRLF / CR to LF.
 * - Trim trailing whitespace on the final line.
 * - Guarantee a single trailing LF.
 *
 * Exported for tests; adapters delegate normalization to this function so
 * every output ends in exactly one newline.
 */
export function normalizeBody(text: string): string {
  const lf = text.replace(/\r\n?/g, LF);
  const trimmed = lf.replace(/[ \t]+\n/g, '\n').replace(/\s+$/g, '');
  return trimmed + LF;
}

/**
 * Section heading for a module, emitted by the runner between separator
 * lines. Exported here so all adapters use the same heading shape.
 */
export function renderModuleHeading(module: ResolvedModule): string {
  return `## Module: ${module.id} (v${module.version})` + LF;
}

/**
 * Standard inter-section separator (`---`) terminated with LF.
 */
export const SECTION_SEPARATOR = '---' + LF;
