/**
 * Tool-parser test for exported files (acceptance criterion I3).
 *
 * Runs `augx export` against the same two-module fixture used by I1 and
 * then loads each generated file with a parser appropriate to the target
 * tool:
 *
 *   - `.cursor/rules/augx.mdc` is parsed with `gray-matter`, which is the
 *     library Cursor's own `.mdc` reader is built on (YAML frontmatter +
 *     Markdown body). Asserts the frontmatter has the required keys
 *     (`description`, `alwaysApply`) and that `alwaysApply` is a boolean
 *     `true`, plus that the body starts with the standard augx banner.
 *   - `CLAUDE.md` (Claude Code) has no frontmatter; it is validated
 *     against a known-good structural schema: banner present, every
 *     mandatory banner key present exactly once, balanced HTML comments,
 *     module headings present, and the canonical footer line present.
 *
 * Together these checks satisfy the test plan's requirement that
 * generated files load cleanly in each tool's parser without errors.
 *
 * See: openspec/changes/cross-platform/tests/test-plan.md (I3)
 * See: openspec/specs/cross-platform/export-command.md (Output Structure)
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import matter from 'gray-matter';
import type { ResolvedModule } from '@cli/adapters/types';

const resolverMocks = vi.hoisted(() => ({
  modules: [] as ResolvedModule[],
}));

vi.mock('@cli/lib/module-resolver', async () => {
  const actual = await vi.importActual<typeof import('@cli/lib/module-resolver')>(
    '@cli/lib/module-resolver'
  );
  return {
    ...actual,
    resolveLinkedModules: () => resolverMocks.modules,
  };
});

import { exportCommand } from '@cli/commands/export';
import { EXIT } from '@cli/lib/export-runner';

const FIXED_TIMESTAMP = '2026-05-25T12:00:00Z';

/** Mirrors the I1 fixture inputs so the two suites stay in lock-step. */
function makeModule(id: string, relPath: string, body: string): ResolvedModule {
  return {
    id,
    version: '1.0.0',
    rootPath: `/virtual/${id}`,
    rulesFiles: [{ relativePath: relPath, content: body }],
    examplesFiles: [],
  };
}

const TS_BODY = '# TS\n\n- strict mode on\n';
const OS_BODY = '# OpenSpec\n\n- draft proposals\n';

describe('augx export: generated files load in tool parsers (I3)', () => {
  let tmp: string;
  let cwdSpy: ReturnType<typeof vi.spyOn>;
  const originalEnv = process.env.AUGX_FAKE_NOW;

  beforeEach(() => {
    tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'augx-i3-'));
    fs.mkdirSync(path.join(tmp, '.augment'), { recursive: true });
    fs.writeFileSync(
      path.join(tmp, '.augment', 'extensions.json'),
      JSON.stringify({ version: '1.0.0', modules: [] }, null, 2),
      'utf-8'
    );
    cwdSpy = vi.spyOn(process, 'cwd').mockReturnValue(tmp);
    process.env.AUGX_FAKE_NOW = FIXED_TIMESTAMP;
    resolverMocks.modules = [
      makeModule(
        'coding-standards/typescript-standards',
        'rules/strict.md',
        TS_BODY
      ),
      makeModule('workflows/openspec-workflow', 'rules/draft.md', OS_BODY),
    ];
    process.exitCode = 0;
  });

  afterEach(() => {
    cwdSpy.mockRestore();
    if (originalEnv === undefined) {
      delete process.env.AUGX_FAKE_NOW;
    } else {
      process.env.AUGX_FAKE_NOW = originalEnv;
    }
    fs.rmSync(tmp, { recursive: true, force: true });
    process.exitCode = 0;
  });

  it('Cursor .mdc parses with gray-matter and has required frontmatter keys', async () => {
    const code = await exportCommand({ target: 'cursor' });
    expect(code).toBe(EXIT.OK);

    const mdcPath = path.join(tmp, '.cursor', 'rules', 'augx.mdc');
    const raw = fs.readFileSync(mdcPath, 'utf-8');

    // gray-matter throws if the YAML block is malformed.
    let parsed: ReturnType<typeof matter>;
    expect(() => {
      parsed = matter(raw);
    }).not.toThrow();

    const data = parsed!.data as Record<string, unknown>;
    expect(Object.keys(data).sort()).toEqual(['alwaysApply', 'description']);
    expect(data.description).toBe('Augx aggregated rules');
    expect(data.alwaysApply).toBe(true);

    // The Markdown body must start with the standard banner immediately
    // after the frontmatter delimiter and include the canonical footer.
    expect(parsed!.content).toMatch(
      /^<!-- GENERATED BY augx export - DO NOT EDIT -->/
    );
    expect(parsed!.content).toMatch(
      /<!-- End of augx-generated content\. Canonical modules: augment-extensions\/modules\/ -->/
    );
  });

  it('CLAUDE.md satisfies the known-good banner + footer schema', async () => {
    const code = await exportCommand({ target: 'claude-code' });
    expect(code).toBe(EXIT.OK);

    const claudePath = path.join(tmp, 'CLAUDE.md');
    const raw = fs.readFileSync(claudePath, 'utf-8');

    // No frontmatter on CLAUDE.md - gray-matter on a fence-less file
    // returns the entire body as `content` and an empty `data` object.
    const parsed = matter(raw);
    expect(parsed.data).toEqual({});
    expect(parsed.content).toBe(raw);

    // Required banner keys, each present exactly once.
    const bannerKeys = [
      /<!-- GENERATED BY augx export - DO NOT EDIT -->/g,
      /<!-- augx-version: [^\n>]+ -->/g,
      /<!-- generated-at: [^\n>]+ -->/g,
      /<!-- source-hash: [0-9a-f]{16} -->/g,
      /<!-- modules: [^\n>]+ -->/g,
    ];
    for (const re of bannerKeys) {
      const hits = raw.match(re);
      expect(hits, `banner pattern ${re} should match`).not.toBeNull();
      expect(hits!.length, `banner pattern ${re} occurs once`).toBe(1);
    }

    // Balanced HTML comments.
    const openers = (raw.match(/<!--/g) ?? []).length;
    const closers = (raw.match(/-->/g) ?? []).length;
    expect(openers).toBe(closers);

    // Module headings present for each linked module.
    expect(raw).toContain('## Module: coding-standards/typescript-standards (v1.0.0)');
    expect(raw).toContain('## Module: workflows/openspec-workflow (v1.0.0)');

    // Canonical footer line.
    expect(raw).toContain(
      '<!-- End of augx-generated content. Canonical modules: augment-extensions/modules/ -->'
    );
  });
});
